models:
  - name: Densenet-121

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   public/densenet-121/densenet-121.prototxt
        weights: public/densenet-121/densenet-121.caffemodel
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        model:   public/densenet-121/densenet-121.prototxt
        weights: public/densenet-121/densenet-121.caffemodel
        backend: OCV
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        model:   public/densenet-121/densenet-121.prototxt
        weights: public/densenet-121/densenet-121.caffemodel
        backend: OCV
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256

          - type: crop
            size: 224

          - type: normalization
            mean: 103.94, 116.78, 123.68
            std:  58.8235294

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1

          - name: accuracy@top5
            type: accuracy
            top_k: 5


  - name: Densenet-161

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   public/densenet-161/densenet-161.prototxt
        weights: public/densenet-161/densenet-161.caffemodel
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        model:   public/densenet-161/densenet-161.prototxt
        weights: public/densenet-161/densenet-161.caffemodel
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        model:   public/densenet-161/densenet-161.prototxt
        weights: public/densenet-161/densenet-161.caffemodel
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256

          - type: crop
            size: 224

          - type: normalization
            mean: 103.94, 116.78, 123.68
            std:  58.8235294

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1

          - name: accuracy@top5
            type: accuracy
            top_k: 5


  - name: Densenet-169

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   public/densenet-169/densenet-169.prototxt
        weights: public/densenet-169/densenet-169.caffemodel
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        model:   public/densenet-169/densenet-169.prototxt
        weights: public/densenet-169/densenet-169.caffemodel
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        model:   public/densenet-169/densenet-169.prototxt
        weights: public/densenet-169/densenet-169.caffemodel
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256

          - type: crop
            size: 224

          - type: normalization
            mean: 103.94, 116.78, 123.68
            std:  58.8235294

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1

          - name: accuracy@top5
            type: accuracy
            top_k: 5


  - name: Densenet-201

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   public/densenet-201/densenet-201.prototxt
        weights: public/densenet-201/densenet-201.caffemodel
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        model:   public/densenet-201/densenet-201.prototxt
        weights: public/densenet-201/densenet-201.caffemodel
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        model:   public/densenet-201/densenet-201.prototxt
        weights: public/densenet-201/densenet-201.caffemodel
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256

          - type: crop
            size: 224

          - type: normalization
            mean: 103.94, 116.78, 123.68
            std:  58.8235294

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1

          - name: accuracy@top5
            type: accuracy
            top_k: 5
