models:
  - name: face-detection-retail-int8-0004

    launchers:
      - framework: opencv
        model:   intel/face-detection-retail-0004/INT8/face-detection-retail-0004.xml
        weights: intel/face-detection-retail-0004/INT8/face-detection-retail-0004.bin
        device: CPU
        tags:
          - FP32
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 300, 300
        adapter: ssd

      - framework: opencv
        model:   intel/face-detection-retail-0004/INT8/face-detection-retail-0004.xml
        weights: intel/face-detection-retail-0004/INT8/face-detection-retail-0004.bin
        device: GPU
        tags:
          - FP32
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 300, 300
        adapter: ssd

      - framework: opencv
        model:   intel/face-detection-retail-0004/INT8/face-detection-retail-0004.xml
        weights: intel/face-detection-retail-0004/INT8/face-detection-retail-0004.bin
        device: GPU
        tags:
          - FP16
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 300, 300
        adapter: ssd

    datasets:
      - name: wider_label_start_1
        data_source: WiderFace/WIDER_val/images
        annotation: widerface_label_start_1.pickle
        dataset_meta: widerface_label_start_1.json

        preprocessing:
          - type: resize
            size: 300

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 60
            is_empty: True
          - type: filter
            min_confidence: 0.0
            apply_to: prediction

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False
