models:
  - name: GoogleNet_v1

    launchers:
      - framework: opencv
        model:   public/googlenet-v1/googlenet-v1.prototxt
        weights: public/googlenet-v1/googlenet-v1.caffemodel
        device: CPU
        tags:
          - FP32
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        model:   public/googlenet-v1/googlenet-v1.prototxt
        weights: public/googlenet-v1/googlenet-v1.caffemodel
        device: GPU
        tags:
          - FP32
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        model:   public/googlenet-v1/googlenet-v1.prototxt
        weights: public/googlenet-v1/googlenet-v1.caffemodel
        device: GPU
        tags:
          - FP16
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256

          - type: crop
            size: 224

          - type: normalization
            mean: 104, 117, 123


  - name: GoogleNet_v2

    launchers:
      - framework: opencv
        model:   public/googlenet-v2/googlenet-v2.prototxt
        weights: public/googlenet-v2/googlenet-v2.caffemodel
        device: CPU
        tags:
          - FP32
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        model:   public/googlenet-v2/googlenet-v2.prototxt
        weights: public/googlenet-v2/googlenet-v2.caffemodel
        device: GPU
        tags:
          - FP32
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        model:   public/googlenet-v2/googlenet-v2.prototxt
        weights: public/googlenet-v2/googlenet-v2.caffemodel
        device: GPU
        tags:
          - FP16
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: imagenet_1000_classes_2015
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256

          - type: crop
            size: 224

          - type: normalization
            mean: 104, 117, 123


  - name: GoogleNet_v4

    launchers:
      - framework: opencv
        model:   public/googlenet-v4/googlenet-v4.prototxt
        weights: public/googlenet-v4/googlenet-v4.caffemodel
        device: CPU
        tags:
          - FP32
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 299, 299
        adapter: classification

      - framework: opencv
        model:   public/googlenet-v4/googlenet-v4.prototxt
        weights: public/googlenet-v4/googlenet-v4.caffemodel
        device: GPU
        tags:
          - FP32
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 299, 299
        adapter: classification

      - framework: opencv
        model:   public/googlenet-v4/googlenet-v4.prototxt
        weights: public/googlenet-v4/googlenet-v4.caffemodel
        device: GPU
        tags:
          - FP16
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 299, 299
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 320

          - type: crop
            size: 299

          - type: normalization
            std: 255
