models:
  - name: mobilenet-v1-0-25-128

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model: public/mobilenet-v1-0.25-128/mobilenet_v1_0.25_128_frozen.pb
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 128, 128
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        model: public/mobilenet-v1-0.25-128/mobilenet_v1_0.25_128_frozen.pb
        backend: OCV
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 128, 128
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        model: public/mobilenet-v1-0.25-128/mobilenet_v1_0.25_128_frozen.pb
        backend: OCV
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 128, 128
        adapter: classification

    datasets:
      - name: imagenet_1001_classes
        data_source: ImageNet

        preprocessing:
          - type: bgr_to_rgb

          - type: resize
            size: 256

          - type: crop
            size: 128

          - type: normalization
            mean: 127.5
            std:  127.5
