models:
  - name: vgg19

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   public/vgg19/vgg19.prototxt
        weights: public/vgg19/vgg19.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        model:   public/vgg19/vgg19.prototxt
        weights: public/vgg19/vgg19.caffemodel
        backend: OCV
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        model:   public/vgg19/vgg19.prototxt
        weights: public/vgg19/vgg19.caffemodel
        backend: OCV
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater

          - type: crop
            size: 224

          - type: normalization
            mean: 103.939, 116.779, 123.68
